source("../R/longData-Partition.r")


cat("###################################################################
#################### Test  LongData & Partition ###################
############################### plot ##############################
###################################################################\n")

cat("### 1 ###\n")
par(mfrow=c(3,4))
plot(ld3)
plot(ld3,p3a)
plot(ld3,p3b,type="n")
plot(ld3,p3c,type="l",col=1)
plot(ld3,p3a,type="l")
plot(ld3,p3a,type.mean="n")
plot(ld3,p3a,col.mean=1,pch.mean="symbols")
plot(ld3,p3a,type="l",type.mean="n",pch.mean="letters")
plot(ld3,p3a,type="n",type.mean="n")
plot(ld3,p3a,type="l",type.mean="b",pch.mean="letters",cex.mean=3)

cat("### 2 ###\n")
par(mfrow=c(3,4))
plot(ld4)
plot(ld4,p4a)
plot(ld4,p4b,type="n")
plot(ld4,p4c,type="l",col=1)
plot(ld4,p4a,type="l")
plot(ld4,p4a,type.mean="n")
plot(ld4,p4a,col.mean=1)
plot(ld4,p4a,legends=FALSE)
plot(ld4,p4a,col.mean=1,pch.mean="symbols")
plot(ld4,p4a,type="l",type.mean="n",pch.mean="letters")
plot(ld4,p4a,type="n",type.mean="n")
plot(ld4,p4a,type="l",type.mean="n",pch.mean="letters",cex.mean=3)
plot(ld4,p4a,legends=FALSE,ylim=c(-30,30))

cat("### 3 ###\n")
par(mfrow=c(3,3))
plot(ld3,p3a,type="l",subGroups="A")
plot(ld3,p3a,type="l",subGroups="B",pch.mean="letters")
plot(ld3,p3a,type="l",subGroups="C")
plot(ld3,p3a,type="l",subGroups=c("A","C"))
plot(ld3,p3a,type="n",subGroups=c("A","C"),type.mean="n")
plot(ld3,p3a,type="n",subGroups=c("A","C"))
plot(ld3,p3a,type="n",subGroups=c("A","C"),type.mean="n",pch.mean="letters")
plot(ld3,p3a,type.mean="n",subGroups=c("A","C","B"))
plot(ld3,p3a,type.mean="n")

cat("### 4 ###\n")
par(mfrow=c(3,4))
plot(ld1)
plot(ld1,type="l",col=1)
plot(ld2)
plot(ld2n)
plot(ld3)
plot(ld3n,type="l",col=1,col.mean=1)
plot(ld4,type="l",col=1)
plot(ld4n,type="l",col=1,pch.mean="symbols")
plot(ld4n,type="l",col=1)
plot(ld5,type="l",col=1)
plot(ld5,type.mean="n",legends=FALSE)
plot(ld5n)

cat("### 5 ###\n")
dev.off()
plotSubGroups(ld3,p3a)
plotSubGroups(ld3,p3b,type.mean="n")
plotSubGroups(ld4,p4a)
plotSubGroups(ld3,p3b,type.mean="b",type="n",pch.mean="letters")


cat("\n++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++++ Fin Test  LongData-Partition +++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n")
